name: build
on:
  push:
    # all branches
    branches:
      - '**'
    # no tags
    tags-ignore:
      - '**'

env:
  NODE_VERSION: 12
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Log versions
      - run: npm --version; node --version
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ./.npmrc
      - run: echo "@cmawhorter:registry=https://npm.pkg.github.com" >> ./.npmrc
      - run: npm i
      - run: npm test
